/** Cloud provider region codes and city/country names → {lat, lng} */

type LatLng = { lat: number; lng: number; label: string }

const REGION_MAP: Record<string, LatLng> = {
  // ── AWS ──────────────────────────────────────────────────────────────────
  'us-east-1':       { lat: 38.89,  lng: -77.04,  label: 'N. Virginia, US' },
  'us-east-2':       { lat: 39.96,  lng: -82.99,  label: 'Ohio, US' },
  'us-west-1':       { lat: 37.33,  lng: -121.9,  label: 'N. California, US' },
  'us-west-2':       { lat: 45.52,  lng: -122.67, label: 'Oregon, US' },
  'ca-central-1':    { lat: 45.50,  lng: -73.56,  label: 'Canada (Central)' },
  'ca-west-1':       { lat: 51.05,  lng: -114.08, label: 'Calgary, Canada' },
  'eu-west-1':       { lat: 53.33,  lng: -6.25,   label: 'Ireland' },
  'eu-west-2':       { lat: 51.51,  lng: -0.13,   label: 'London, UK' },
  'eu-west-3':       { lat: 48.86,  lng: 2.35,    label: 'Paris, France' },
  'eu-central-1':    { lat: 50.11,  lng: 8.68,    label: 'Frankfurt, Germany' },
  'eu-south-1':      { lat: 45.46,  lng: 9.19,    label: 'Milan, Italy' },
  'eu-north-1':      { lat: 59.33,  lng: 18.07,   label: 'Stockholm, Sweden' },
  'eusc-de-east-1':  { lat: 51.05,  lng: 13.74,   label: 'Dresden, Germany (Sovereign)' },
  'ap-southeast-1':  { lat: 1.35,   lng: 103.82,  label: 'Singapore' },
  'ap-southeast-2':  { lat: -33.87, lng: 151.21,  label: 'Sydney, Australia' },
  'ap-southeast-3':  { lat: -6.21,  lng: 106.85,  label: 'Jakarta, Indonesia' },
  'ap-southeast-4':  { lat: -37.81, lng: 144.96,  label: 'Melbourne, Australia' },
  'ap-northeast-1':  { lat: 35.69,  lng: 139.69,  label: 'Tokyo, Japan' },
  'ap-northeast-3':  { lat: 34.69,  lng: 135.50,  label: 'Osaka, Japan' },
  'ap-south-1':      { lat: 19.08,  lng: 72.88,   label: 'Mumbai, India' },
  'ap-east-1':       { lat: 22.32,  lng: 114.17,  label: 'Hong Kong' },
  'sa-east-1':       { lat: -23.55, lng: -46.63,  label: 'São Paulo, Brazil' },
  'me-south-1':      { lat: 26.21,  lng: 50.59,   label: 'Bahrain' },
  'me-central-1':    { lat: 25.20,  lng: 55.27,   label: 'UAE' },
  'af-south-1':      { lat: -33.92, lng: 18.42,   label: 'Cape Town, South Africa' },
  'cn-north-1':      { lat: 39.91,  lng: 116.39,  label: 'Beijing, China' },
  'us-gov-east-1':   { lat: 38.89,  lng: -77.04,  label: 'US GovCloud (East)' },
  'us-gov-west-1':   { lat: 45.52,  lng: -122.67, label: 'US GovCloud (West)' },

  // ── GCP ──────────────────────────────────────────────────────────────────
  'us-central1':            { lat: 41.60,  lng: -93.61,  label: 'Iowa, US' },
  'us-east1':               { lat: 33.20,  lng: -79.93,  label: 'S. Carolina, US' },
  'us-east4':               { lat: 38.89,  lng: -77.04,  label: 'N. Virginia, US' },
  'us-west1':               { lat: 45.60,  lng: -121.18, label: 'Oregon, US' },
  'us-west2':               { lat: 34.05,  lng: -118.24, label: 'Los Angeles, US' },
  'us-west4':               { lat: 36.17,  lng: -115.14, label: 'Las Vegas, US' },
  'europe-west1':           { lat: 50.45,  lng: 3.82,    label: 'Belgium' },
  'europe-west2':           { lat: 51.51,  lng: -0.13,   label: 'London, UK' },
  'europe-west3':           { lat: 50.11,  lng: 8.68,    label: 'Frankfurt, Germany' },
  'europe-west4':           { lat: 52.38,  lng: 4.90,    label: 'Netherlands' },
  'europe-west6':           { lat: 47.38,  lng: 8.54,    label: 'Zurich, Switzerland' },
  'europe-north1':          { lat: 60.57,  lng: 27.82,   label: 'Finland' },
  'northamerica-northeast1':{ lat: 45.50,  lng: -73.56,  label: 'Montréal, Canada' },
  'northamerica-northeast2':{ lat: 43.70,  lng: -79.42,  label: 'Toronto, Canada' },
  'asia-east1':             { lat: 24.05,  lng: 120.55,  label: 'Taiwan' },
  'asia-northeast1':        { lat: 35.69,  lng: 139.69,  label: 'Tokyo, Japan' },
  'asia-south1':            { lat: 19.08,  lng: 72.88,   label: 'Mumbai, India' },
  'asia-southeast1':        { lat: 1.35,   lng: 103.82,  label: 'Singapore' },
  'asia-southeast2':        { lat: -6.21,  lng: 106.85,  label: 'Jakarta, Indonesia' },
  'australia-southeast1':   { lat: -33.87, lng: 151.21,  label: 'Sydney, Australia' },
  'southamerica-east1':     { lat: -23.55, lng: -46.63,  label: 'São Paulo, Brazil' },
  'me-west1':               { lat: 32.09,  lng: 34.79,   label: 'Tel Aviv, Israel' },
  'me-central1':            { lat: 25.20,  lng: 55.27,   label: 'UAE' },
  'me-central2':            { lat: 25.29,  lng: 51.53,   label: 'Qatar' },

  // ── Azure ─────────────────────────────────────────────────────────────────
  'eastus':               { lat: 37.36,  lng: -79.38,  label: 'Virginia, US' },
  'eastus2':              { lat: 36.67,  lng: -78.36,  label: 'Virginia, US' },
  'east us':              { lat: 37.36,  lng: -79.38,  label: 'Virginia, US' },
  'east us 2':            { lat: 36.67,  lng: -78.36,  label: 'Virginia, US' },
  'east us / east us 2':  { lat: 37.00,  lng: -79.00,  label: 'Virginia, US' },
  'westus':               { lat: 37.78,  lng: -122.42, label: 'California, US' },
  'westus2':              { lat: 47.23,  lng: -120.05, label: 'Washington, US' },
  'centralus':            { lat: 41.60,  lng: -93.61,  label: 'Iowa, US' },
  'central us':           { lat: 41.60,  lng: -93.61,  label: 'Iowa, US' },
  'canadacentral':        { lat: 43.70,  lng: -79.42,  label: 'Toronto, Canada' },
  'canada central':       { lat: 43.70,  lng: -79.42,  label: 'Toronto, Canada' },
  'westeurope':           { lat: 52.38,  lng: 4.90,    label: 'Netherlands' },
  'west europe':          { lat: 52.38,  lng: 4.90,    label: 'Netherlands' },
  'northeurope':          { lat: 53.33,  lng: -6.25,   label: 'Ireland' },
  'uksouth':              { lat: 51.51,  lng: -0.13,   label: 'London, UK' },
  'united kingdomsouth':  { lat: 51.51,  lng: -0.13,   label: 'London, UK' },
  'ukwest':               { lat: 53.48,  lng: -2.24,   label: 'Cardiff, UK' },
  'francecentral':        { lat: 46.31,  lng: 2.35,    label: 'Paris, France' },
  'france central':       { lat: 46.31,  lng: 2.35,    label: 'Paris, France' },
  'germanywestcentral':   { lat: 50.11,  lng: 8.68,    label: 'Frankfurt, Germany' },
  'swedencentral':        { lat: 60.67,  lng: 17.12,   label: 'Sweden' },
  'switzerlandnorth':     { lat: 47.45,  lng: 8.56,    label: 'Zurich, Switzerland' },
  'australiaeast':        { lat: -33.87, lng: 151.21,  label: 'Sydney, Australia' },
  'australia-southeast':  { lat: -37.81, lng: 144.96,  label: 'Melbourne, Australia' },
  'eastasia':             { lat: 22.32,  lng: 114.17,  label: 'Hong Kong' },
  'east asia':            { lat: 22.32,  lng: 114.17,  label: 'Hong Kong' },
  'southeastasia':        { lat: 1.35,   lng: 103.82,  label: 'Singapore' },
  'japaneast':            { lat: 35.69,  lng: 139.69,  label: 'Tokyo, Japan' },
  'koreacentral':         { lat: 37.56,  lng: 126.98,  label: 'Seoul, South Korea' },
  'centralindia':         { lat: 18.52,  lng: 73.86,   label: 'Pune, India' },
  'southindia':           { lat: 13.08,  lng: 80.27,   label: 'Chennai, India' },
  'brazilsouth':          { lat: -23.55, lng: -46.63,  label: 'São Paulo, Brazil' },
  'southafricanorth':     { lat: -26.11, lng: 28.05,   label: 'Johannesburg, South Africa' },
  'uaenorth':             { lat: 25.20,  lng: 55.27,   label: 'Dubai, UAE' },
  'uae-north':            { lat: 25.20,  lng: 55.27,   label: 'Dubai, UAE' },
  'an-northeast-1':       { lat: 35.69,  lng: 139.69,  label: 'Tokyo, Japan' },

  // ── Data center codes (OpenText / legacy) ─────────────────────────────
  'ams':   { lat: 52.38,  lng: 4.90,    label: 'Amsterdam, Netherlands' },
  'at1':   { lat: 47.80,  lng: 13.04,   label: 'Linz, Austria' },
  'dal':   { lat: 32.78,  lng: -96.80,  label: 'Dallas, US' },
  'lit':   { lat: 33.76,  lng: -84.40,  label: 'Lithia Springs, US' },
  'muc':   { lat: 48.14,  lng: 11.58,   label: 'Munich, Germany' },
  'syd':   { lat: -33.87, lng: 151.21,  label: 'Sydney, Australia' },
  'tok':   { lat: 35.69,  lng: 139.69,  label: 'Tokyo, Japan' },
  'wok':   { lat: 51.32,  lng: -0.56,   label: 'Woking, UK' },
}

const CITY_COUNTRY_MAP: Record<string, LatLng> = {
  'ashburn|united states':       { lat: 38.89,  lng: -77.04,  label: 'Ashburn, US' },
  'allen|united states':         { lat: 33.10,  lng: -96.67,  label: 'Allen, TX, US' },
  'atlanta|united states':       { lat: 33.75,  lng: -84.39,  label: 'Atlanta, US' },
  'boardman|united states':      { lat: 45.84,  lng: -119.70, label: 'Boardman, OR, US' },
  'boardmen|united states':      { lat: 45.84,  lng: -119.70, label: 'Boardman, OR, US' },
  'boardman / hermiston|united states': { lat: 45.84, lng: -119.70, label: 'Boardman, OR, US' },
  'boydton|united states':       { lat: 36.67,  lng: -78.38,  label: 'Boydton, US' },
  'boydton / ashburn|united states':    { lat: 37.36, lng: -79.38, label: 'Virginia, US' },
  'boyers|united states':        { lat: 41.10,  lng: -79.92,  label: 'Boyers, PA, US' },
  'brook park|united states':    { lat: 41.40,  lng: -81.80,  label: 'Brook Park, OH, US' },
  'calgary|canada':              { lat: 51.05,  lng: -114.07, label: 'Calgary, Canada' },
  'chandler|united states':      { lat: 33.30,  lng: -111.84, label: 'Chandler, AZ, US' },
  'chicago|united states':       { lat: 41.88,  lng: -87.63,  label: 'Chicago, US' },
  'council bluffs|united states':{ lat: 41.26,  lng: -95.86,  label: 'Council Bluffs, IA, US' },
  'council bluffs area|united states': { lat: 41.26, lng: -95.86, label: 'Council Bluffs, IA, US' },
  'dallas|united states':        { lat: 32.78,  lng: -96.80,  label: 'Dallas, US' },
  'des moines|united states':    { lat: 41.59,  lng: -93.62,  label: 'Des Moines, IA, US' },
  'las vegas|united states':     { lat: 36.17,  lng: -115.14, label: 'Las Vegas, US' },
  'lithia springs|united states':{ lat: 33.79,  lng: -84.66,  label: 'Lithia Springs, GA, US' },
  'los angeles|united states':   { lat: 34.05,  lng: -118.24, label: 'Los Angeles, US' },
  'moncks corner|united states': { lat: 33.20,  lng: -79.99,  label: 'Moncks Corner, SC, US' },
  'northern|united states':      { lat: 38.89,  lng: -77.04,  label: 'Northern Virginia, US' },
  'portland|united states':      { lat: 45.52,  lng: -122.68, label: 'Portland, OR, US' },
  'san francisco|united states': { lat: 37.77,  lng: -122.42, label: 'San Francisco, US' },
  'san jose|united states':      { lat: 37.34,  lng: -121.89, label: 'San Jose, US' },
  'smyrna|united states':        { lat: 33.88,  lng: -84.52,  label: 'Smyrna, GA, US' },
  'the dalles|united states':    { lat: 45.60,  lng: -121.19, label: 'The Dalles, OR, US' },
  'tinton falls|united states':  { lat: 40.26,  lng: -74.09,  label: 'Tinton Falls, NJ, US' },
  'tukwila|united states':       { lat: 47.46,  lng: -122.26, label: 'Tukwila, WA, US' },
  'mississauga|canada':          { lat: 43.59,  lng: -79.64,  label: 'Mississauga, Canada' },
  'montreal|canada':             { lat: 45.50,  lng: -73.56,  label: 'Montréal, Canada' },
  'montréal|canada':             { lat: 45.50,  lng: -73.56,  label: 'Montréal, Canada' },
  'toronto|canada':              { lat: 43.70,  lng: -79.42,  label: 'Toronto, Canada' },
  'amsterdam|netherlands':       { lat: 52.37,  lng: 4.90,    label: 'Amsterdam, Netherlands' },
  'amstelveen|netherlands':      { lat: 52.31,  lng: 4.87,    label: 'Amstelveen, Netherlands' },
  'eemshaven|netherlands':       { lat: 53.44,  lng: 6.84,    label: 'Eemshaven, Netherlands' },
  'bracknell|united kingdom':    { lat: 51.41,  lng: -0.75,   label: 'Bracknell, UK' },
  'chessington|united kingdom':  { lat: 51.37,  lng: -0.31,   label: 'Chessington, UK' },
  'london|united kingdom':       { lat: 51.51,  lng: -0.13,   label: 'London, UK' },
  'slough|united kingdom':       { lat: 51.51,  lng: -0.59,   label: 'Slough, UK' },
  'woking|united kingdom':       { lat: 51.32,  lng: -0.56,   label: 'Woking, UK' },
  'frankfurt|germany':           { lat: 50.11,  lng: 8.68,    label: 'Frankfurt, Germany' },
  'munich|germany':              { lat: 48.14,  lng: 11.58,   label: 'Munich, Germany' },
  'potsdam|germany':             { lat: 52.40,  lng: 13.06,   label: 'Potsdam, Germany' },
  'hamina|finland':              { lat: 60.57,  lng: 27.19,   label: 'Hamina, Finland' },
  'helsinki|finland':            { lat: 60.17,  lng: 24.94,   label: 'Helsinki, Finland' },
  'paris|france':                { lat: 48.86,  lng: 2.35,    label: 'Paris, France' },
  'saint-ghislain|belgium':      { lat: 50.45,  lng: 3.82,    label: 'Saint-Ghislain, Belgium' },
  'stockholm|sweden':            { lat: 59.33,  lng: 18.07,   label: 'Stockholm, Sweden' },
  'zurich|switzerland':          { lat: 47.38,  lng: 8.54,    label: 'Zurich, Switzerland' },
  'lupfig|switzerland':          { lat: 47.44,  lng: 8.17,    label: 'Lupfig, Switzerland' },
  'osaka|japan':                 { lat: 34.69,  lng: 135.50,  label: 'Osaka, Japan' },
  'tokyo|japan':                 { lat: 35.69,  lng: 139.69,  label: 'Tokyo, Japan' },
  'singapore|singapore':         { lat: 1.35,   lng: 103.82,  label: 'Singapore' },
  'jurong west|singapore':       { lat: 1.34,   lng: 103.71,  label: 'Jurong West, Singapore' },
  'jakarta|indonesia':           { lat: -6.21,  lng: 106.85,  label: 'Jakarta, Indonesia' },
  'kuala lumpur|malaysia':       { lat: 3.14,   lng: 101.69,  label: 'Kuala Lumpur, Malaysia' },
  'hong kong|hong kong':         { lat: 22.32,  lng: 114.17,  label: 'Hong Kong' },
  'mumbai|india':                { lat: 19.08,  lng: 72.88,   label: 'Mumbai, India' },
  'sydney|australia':            { lat: -33.87, lng: 151.21,  label: 'Sydney, Australia' },
  'melbourne|australia':         { lat: -37.81, lng: 144.96,  label: 'Melbourne, Australia' },
  'cape town|south africa':      { lat: -33.92, lng: 18.42,   label: 'Cape Town, South Africa' },
  'capetown|south africa':       { lat: -33.92, lng: 18.42,   label: 'Cape Town, South Africa' },
  'johannesburg|south africa':   { lat: -26.11, lng: 28.05,   label: 'Johannesburg, South Africa' },
  'osasco|brazil':               { lat: -23.53, lng: -46.79,  label: 'Osasco, Brazil' },
  'sao paulo|brazil':            { lat: -23.55, lng: -46.63,  label: 'São Paulo, Brazil' },
  'dubai|united arab emirates':  { lat: 25.20,  lng: 55.27,   label: 'Dubai, UAE' },
  'bahrain|bahrain':             { lat: 26.21,  lng: 50.59,   label: 'Bahrain' },
  'dammam|saudi arabia':         { lat: 26.39,  lng: 50.00,   label: 'Dammam, KSA' },
  'doha|qatar':                  { lat: 25.29,  lng: 51.53,   label: 'Doha, Qatar' },
  'tel aviv|israel':             { lat: 32.09,  lng: 34.79,   label: 'Tel Aviv, Israel' },
  'beijing|china':               { lat: 39.91,  lng: 116.39,  label: 'Beijing, China' },
  'shanghai|china':              { lat: 31.23,  lng: 121.47,  label: 'Shanghai, China' },
}

export function resolveGeo(
  region: string,
  city: string,
  country: string,
): LatLng | null {
  const regionKey = region.trim().toLowerCase()
  if (REGION_MAP[regionKey]) return REGION_MAP[regionKey]

  const cityKey = `${city.trim().toLowerCase()}|${country.trim().toLowerCase()}`
  if (CITY_COUNTRY_MAP[cityKey]) return CITY_COUNTRY_MAP[cityKey]

  // Country-level fallback centroids
  const COUNTRY_CENTROIDS: Record<string, LatLng> = {
    'united states':       { lat: 37.09,  lng: -95.71, label: country },
    'canada':              { lat: 56.13,  lng: -106.35, label: country },
    'united kingdom':      { lat: 55.38,  lng: -3.44,  label: country },
    'germany':             { lat: 51.16,  lng: 10.45,  label: country },
    'france':              { lat: 46.23,  lng: 2.21,   label: country },
    'netherlands':         { lat: 52.13,  lng: 5.29,   label: country },
    'ireland':             { lat: 53.41,  lng: -8.24,  label: country },
    'sweden':              { lat: 60.13,  lng: 18.64,  label: country },
    'finland':             { lat: 61.92,  lng: 25.75,  label: country },
    'switzerland':         { lat: 46.82,  lng: 8.23,   label: country },
    'belgium':             { lat: 50.50,  lng: 4.47,   label: country },
    'india':               { lat: 20.59,  lng: 78.96,  label: country },
    'china':               { lat: 35.86,  lng: 104.20, label: country },
    'japan':               { lat: 36.20,  lng: 138.25, label: country },
    'australia':           { lat: -25.27, lng: 133.78, label: country },
    'singapore':           { lat: 1.35,   lng: 103.82, label: country },
    'indonesia':           { lat: -0.79,  lng: 113.92, label: country },
    'malaysia':            { lat: 4.21,   lng: 101.98, label: country },
    'brazil':              { lat: -14.24, lng: -51.93, label: country },
    'south africa':        { lat: -30.56, lng: 22.94,  label: country },
    'saudi arabia':        { lat: 23.89,  lng: 45.08,  label: country },
    'ksa':                 { lat: 23.89,  lng: 45.08,  label: 'KSA' },
    'united arab emirates':{ lat: 23.42,  lng: 53.85,  label: country },
    'bahrain':             { lat: 25.93,  lng: 50.64,  label: country },
    'qatar':               { lat: 25.35,  lng: 51.18,  label: country },
    'israel':              { lat: 31.05,  lng: 34.85,  label: country },
  }

  const countryKey = country.trim().toLowerCase()
  return COUNTRY_CENTROIDS[countryKey] ?? null
}
